# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/cmi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/cmi

PRODUCT_COPY_FILES += \
    vendor/xiaomi/cmi/proprietary/vendor/etc/camera/CFR_para_T_4x_V03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T_4x_V03.bin \
    vendor/xiaomi/cmi/proprietary/vendor/etc/camera/CFR_para_UW_V03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW_V03.bin \
    vendor/xiaomi/cmi/proprietary/vendor/etc/camera/com.xiaomi.dcal.wt.fake:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wt.fake \
    vendor/xiaomi/cmi/proprietary/vendor/etc/camera/com.xiaomi.dcal.wt4x.fake:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wt4x.fake \
    vendor/xiaomi/cmi/proprietary/vendor/etc/camera/multianchor.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/multianchor.txt \
    vendor/xiaomi/cmi/proprietary/vendor/firmware/cmi_tele4x_ois.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/cmi_tele4x_ois.coeff \
    vendor/xiaomi/cmi/proprietary/vendor/firmware/cmi_tele4x_ois.mem:$(TARGET_COPY_OUT_VENDOR)/firmware/cmi_tele4x_ois.mem \
    vendor/xiaomi/cmi/proprietary/vendor/firmware/cmi_tele4x_ois.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/cmi_tele4x_ois.prog \
    vendor/xiaomi/cmi/proprietary/vendor/firmware/cmi_wide_ois.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/cmi_wide_ois.coeff \
    vendor/xiaomi/cmi/proprietary/vendor/firmware/cmi_wide_ois.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/cmi_wide_ois.prog \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.actuator.cmi_sunny_ultra_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.actuator.cmi_sunny_ultra_dw9800.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_ofilm_s5k3t2_gt24p64.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_ofilm_s5k3t2_gt24p64.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_semco_ov08a10_m24c64.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_semco_ov08a10_m24c64.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_semco_ov08a10_m24c64x.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_semco_ov08a10_m24c64x.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_semco_s5k2l7_m24c64x.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_semco_s5k2l7_m24c64x.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_semco_s5khmx_m24c128.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_semco_s5khmx_m24c128.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_semco_s5khmx_m24c128x.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_semco_s5khmx_m24c128x.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_semco_s5khmx_m24c64.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_semco_s5khmx_m24c64.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_sunny_imx350_gt24p64b.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_sunny_imx350_gt24p64b.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.cmi_sunny_s5k5e8yx_gt24p64.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.cmi_sunny_s5k5e8yx_gt24p64.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.eeprom.hawkeye_semco_ov48c_m24c64x.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.hawkeye_semco_ov48c_m24c64x.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.cmi_s5k5e8yx_macro.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.cmi_s5k5e8yx_macro.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.imx350_cmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.imx350_cmi.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.ov08a10_cmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.ov08a10_cmi.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.ov48c_hawkeye.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.ov48c_hawkeye.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.s5k2l7_cmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.s5k2l7_cmi.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.s5k3t2_cmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.s5k3t2_cmi.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.s5khmx_cmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.s5khmx_cmi.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensor.s5khmx_wide_cmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.s5khmx_wide_cmi.so \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.cmi_ofilm_s5k3t2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cmi_ofilm_s5k3t2.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.cmi_semco_ov08a10_tele4x_v1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cmi_semco_ov08a10_tele4x_v1.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.cmi_semco_s5k2l7_tele2x.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cmi_semco_s5k2l7_tele2x.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.cmi_semco_s5khmx_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cmi_semco_s5khmx_wide.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.cmi_semco_s5khmx_wide_v1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cmi_semco_s5khmx_wide_v1.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.cmi_sunny_imx350_ultra_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cmi_sunny_imx350_ultra_wide.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.sensormodule.hawkeye_semco_ov48c_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.hawkeye_semco_ov48c_wide.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.tuned.cmi_ofilm_s5k3t2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.cmi_ofilm_s5k3t2.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.tuned.cmi_semco_ov08a10_tele4x.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.cmi_semco_ov08a10_tele4x.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.tuned.cmi_semco_s5k2l7_tele2x.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.cmi_semco_s5k2l7_tele2x.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.tuned.cmi_semco_s5khmx_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.cmi_semco_s5khmx_wide.bin \
    vendor/xiaomi/cmi/proprietary/vendor/lib64/camera/com.qti.tuned.cmi_sunny_imx350_ultra_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.cmi_sunny_imx350_ultra_wide.bin
